### ISSUE TITLE
Heroku deployment failing to start

### ISSUE THREAD

**Issue by kevingelion** [GitbookIO/nuts#134]
Just clicked the `Deploy to Heroku` button in the README and am getting the following in the logs when the dyno starts:

```
2017-02-22T17:25:49.319937+00:00 app[web.1]:     at Request.self.callback (/app/node_modules/octocat/node_modules/request/request.js:198:22)
2017-02-22T17:25:49.319938+00:00 app[web.1]:     at emitTwo (events.js:106:13)
2017-02-22T17:25:49.319939+00:00 app[web.1]:     at Request.emit (events.js:191:7)
2017-02-22T17:25:49.319940+00:00 app[web.1]:     at Request.<anonymous> (/app/node_modules/octocat/node_modules/request/request.js:1063:14)
2017-02-22T17:25:49.319941+00:00 app[web.1]:     at Request.emit (events.js:188:7)
2017-02-22T17:25:49.319942+00:00 app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/octocat/node_modules/request/request.js:1009:12)
2017-02-22T17:25:49.319940+00:00 app[web.1]:     at emitOne (events.js:101:20)
2017-02-22T17:25:49.417748+00:00 heroku[web.1]: State changed from starting to crashed
2017-02-22T17:25:49.402416+00:00 heroku[web.1]: Process exited with status 1
```

**Comment by cdesch** [comment]
I've tried deploying it several times and failed. Any Luck getting it to work from the heroku button?


```
Mar 25 13:54:35 myrewardsupdater heroku/router:  at=error code=H10 desc="App crashed" method=GET path="/" host=myrewardsupdater.herokuapp.com request_id=e975268f-d1cc-4e71-8fd6-78c869755c27 fwd="70.192.74.97" dyno= connect= service= status=503 bytes= protocol=https 
Mar 25 13:54:36 myrewardsupdater heroku/router:  at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=myrewardsupdater.herokuapp.com request_id=7befc6ec-9447-4b84-86ab-fba511b32ea2 fwd="70.192.74.97" dyno= connect= service= status=503 bytes= protocol=https 
```

**Comment by cdesch** [comment]
It seems the code isn't getting loaded in my case:

```
 cjs-MBP15:projects cj$ git clone https://git.heroku.com/myrewardsupdater.git
Cloning into 'myrewardsupdater'...
warning: You appear to have cloned an empty repository.
cjs-MBP15:projects cj$ 

```

**Comment by Ratismal** [comment]
After quite a bit of tinkering with this issue, I realized that the GITHUB_REPO variable isn't a full URL. Rather, it's the repository's Author/Name ID.

So for example, if it were this repository it would be `GitbookIO/nuts` instead of `https://github.com/GitbookIO/nuts`

**Comment by dreammaker** [comment]
For anyone else running into this error... Another thing that would cause the H10 "App crashed" error is if the GitHub token you were using in your environment variables gets revoked.  I started seeing what cdesch described in my Heroku logs, seemingly out of the blue.  I hadn't changed the app.  The thing that changed was GitHub permissions.
