### ISSUE TITLE
Undefined Error

### ISSUE THREAD

**Issue by Micua** [GitbookIO/nuts#64]
## ReferenceError: versions is not defined
- at [...]/serve/node_modules/nuts-serve/lib/nuts.js:166:16
- at _rejected ([...]/serve/node_modules/octocat/node_modules/q/q.js:844:24)
- at [...]/serve/node_modules/octocat/node_modules/q/q.js:870:30
- at Promise.when ([...]/serve/node_modules/octocat/node_modules/q/q.js:1122:31)
- at Promise.promise.promiseDispatch ([...]/serve/node_modules/octocat/node_modules/q/q.- js:788:41)
- at [...]/serve/node_modules/octocat/node_modules/q/q.js:604:44
- at runSingle ([...]/serve/node_modules/octocat/node_modules/q/q.js:137:13)
- at flush ([...]/serve/node_modules/octocat/node_modules/q/q.js:125:13)
- at _combinedTickCallback (internal/process/next_tick.js:67:7)
- at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by TakenPilot** [comment]
I'm getting the same error when the index page `/` is visited.
