### ISSUE TITLE
Heroku Deploy Broken

### ISSUE THREAD

**Issue by runspired** [GitbookIO/nuts#90]
Clicking the Heroku Deploy button from the docs leads to the following console error on heroku, I'm not sure if this is on you or them.  The error appears to originate in their code.

```
longboard-classic.heroku.com/github/account/integration/:1 GET https://longboard-classic.heroku.com/github/account/integration/ 404 (Not Found)
ember.prod.js:29144SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at https://d39g7yxq73p8i2.cloudfront.net/assets/dashboard-8b6438b1964d5e4832ae5c1ad0e45404.js:16:24339
    at y (https://d39g7yxq73p8i2.cloudfront.net/assets/vendor-f769b9e85222fd33990db4f4a1a32575.js:18:30923)
    at b (https://d39g7yxq73p8i2.cloudfront.net/assets/vendor-f769b9e85222fd33990db4f4a1a32575.js:18:31018)
    at g (https://d39g7yxq73p8i2.cloudfront.net/assets/vendor-f769b9e85222fd33990db4f4a1a32575.js:18:30826)
    at https://d39g7yxq73p8i2.cloudfront.net/assets/vendor-f769b9e85222fd33990db4f4a1a32575.js:13:23908
    at r.invoke (https://d39g7yxq73p8i2.cloudfront.net/assets/vendor-f769b9e85222fd33990db4f4a1a32575.js:6:6711)
    at Object.r.flush (https://d39g7yxq73p8i2.cloudfront.net/assets/vendor-f769b9e85222fd33990db4f4a1a32575.js:6:7243)
    at Object.n.flush (https://d39g7yxq73p8i2.cloudfront.net/assets/vendor-f769b9e85222fd33990db4f4a1a32575.js:6:5272)
    at Object.o.end (https://d39g7yxq73p8i2.cloudfront.net/assets/vendor-f769b9e85222fd33990db4f4a1a32575.js:5:31223)a @ ember.prod.js:29144e.default.trigger @ ember.prod.js:49166(anonymous function) @ ember.prod.js:50160r.invoke @ ember.prod.js:978r.flush @ ember.prod.js:1042n.flush @ ember.prod.js:838o.end @ ember.prod.js:166(anonymous function) @ ember.prod.js:675
```

**Comment by amilajack** [comment]
I'm getting the same error

**Comment by salomvary** [comment]
I'm seeing the same error :(

**Comment by runspired** [comment]
I believe I got around this by using the link in the ReadMe instead of the one in the docs.

**Comment by salomvary** [comment]
However this only affects the Deploy to Heroku button on Gitbooks: https://nuts.gitbook.com/deploy.html

The one on the README works, but only if you are on the repo URL, not on the README one:

works: https://github.com/GitbookIO/nuts
does not work: https://github.com/GitbookIO/nuts/blob/master/README.md
